baseurl = "https://yu-kosame.github.io/"
languageCode = "en-us"
title = "解析屋こさめ"
theme= "hugo-theme-geppaku"
googleAnalytics = "UA-46740427-3"
disqusShortname = ""

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "yu.kosame"

    # Please set account ids
    # This is Optional values
    twitter  = "spatial_news"
    linkedin = ""
    github   = "yu-kosame"
    tumblr   = ""
    mail     = "info.kosame@gmail.com"

[params]
    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = false
        facebook = false
        tumblr   = false
        hatena   = false # hatena is Japanese social media
        google   = false
        pocket   = false
        # Please set id when you want to display facebook
        facebookAppId = "1837105893223282"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        # sidebar = "adsense/sidebar.html"
        # content = "adsense/content.html"